import ts from "typescript"

export function generateConfigReqistry({
  configPaths,
}: {
  configPaths: string[]
}) {
  const { factory } = ts
  return [
    ...configPaths.map((path, index) =>
      factory.createImportDeclaration(
        undefined,
        factory.createImportClause(
          false,
          undefined,
          factory.createNamedImports([
            factory.createImportSpecifier(
              false,
              factory.createIdentifier("hiveConfig"),
              factory.createIdentifier(`config_${index}`)
            ),
          ])
        ),
        factory.createStringLiteral(`./${path}`)
      )
    ),

    factory.createVariableStatement(
      [factory.createToken(ts.SyntaxKind.ExportKeyword)],
      factory.createVariableDeclarationList(
        [
          factory.createVariableDeclaration(
            factory.createIdentifier("allConfigs"),
            undefined,
            undefined,
            factory.createAsExpression(
              factory.createArrayLiteralExpression(
                configPaths.map((_, index) =>
                  factory.createIdentifier(`config_${index}`)
                ),
                true
              ),
              factory.createTypeReferenceNode(factory.createIdentifier("const"))
            )
          ),
        ],
        ts.NodeFlags.Const
      )
    ),
    factory.createTypeAliasDeclaration(
      [factory.createToken(ts.SyntaxKind.ExportKeyword)],
      factory.createIdentifier("AvailableCatalogs"),
      undefined,
      factory.createIndexedAccessTypeNode(
        factory.createIndexedAccessTypeNode(
          factory.createParenthesizedType(
            factory.createTypeQueryNode(factory.createIdentifier("allConfigs"))
          ),
          factory.createKeywordTypeNode(ts.SyntaxKind.NumberKeyword)
        ),
        factory.createLiteralTypeNode(factory.createStringLiteral("catalog"))
      )
    ),
    factory.createTypeAliasDeclaration(
      [factory.createToken(ts.SyntaxKind.ExportKeyword)],
      factory.createIdentifier("AvailableSchemas"),
      undefined,
      factory.createIndexedAccessTypeNode(
        factory.createIndexedAccessTypeNode(
          factory.createParenthesizedType(
            factory.createTypeQueryNode(factory.createIdentifier("allConfigs"))
          ),
          factory.createKeywordTypeNode(ts.SyntaxKind.NumberKeyword)
        ),
        factory.createLiteralTypeNode(factory.createStringLiteral("schema"))
      )
    ),
    factory.createTypeAliasDeclaration(
      [factory.createToken(ts.SyntaxKind.ExportKeyword)],
      factory.createIdentifier("AvailableTables"),
      undefined,
      factory.createIndexedAccessTypeNode(
        factory.createIndexedAccessTypeNode(
          factory.createParenthesizedType(
            factory.createTypeQueryNode(factory.createIdentifier("allConfigs"))
          ),
          factory.createKeywordTypeNode(ts.SyntaxKind.NumberKeyword)
        ),
        factory.createLiteralTypeNode(factory.createStringLiteral("tableName"))
      )
    ),
    factory.createTypeAliasDeclaration(
      [factory.createToken(ts.SyntaxKind.ExportKeyword)],
      factory.createIdentifier("TablesForCatalogAndSchema"),
      [
        factory.createTypeParameterDeclaration(
          undefined,
          factory.createIdentifier("C"),
          factory.createTypeReferenceNode(
            factory.createIdentifier("AvailableCatalogs")
          )
        ),
        factory.createTypeParameterDeclaration(
          undefined,
          factory.createIdentifier("S"),
          factory.createTypeReferenceNode(
            factory.createIdentifier("AvailableSchemas")
          )
        ),
      ],
      factory.createIndexedAccessTypeNode(
        factory.createTypeReferenceNode(factory.createIdentifier("Extract"), [
          factory.createIndexedAccessTypeNode(
            factory.createParenthesizedType(
              factory.createTypeQueryNode(
                factory.createIdentifier("allConfigs")
              )
            ),
            factory.createKeywordTypeNode(ts.SyntaxKind.NumberKeyword)
          ),
          factory.createTypeLiteralNode([
            factory.createPropertySignature(
              undefined,
              factory.createIdentifier("catalog"),
              undefined,
              factory.createTypeReferenceNode(factory.createIdentifier("C"))
            ),
            factory.createPropertySignature(
              undefined,
              factory.createIdentifier("schema"),
              undefined,
              factory.createTypeReferenceNode(factory.createIdentifier("S"))
            ),
          ]),
        ]),
        factory.createLiteralTypeNode(factory.createStringLiteral("tableName"))
      )
    ),
  ]
}
