export enum State {
  "QUEUED" = "QUEUED",
  "PLANNING" = "PLANNING",
  "STARTING" = "STARTING",
  "RUNNING" = "RUNNING",
  "FINISHED" = "FINISHED",
  "CANCELED" = "CANCELED",
  "FAILED" = "FAILED",
}
