name: Tegami PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/setup

      - name: Release preview
        run: pnpm tegami pr preview --artifact tegami-pr-preview.md

      - uses: actions/upload-artifact@v7
        with:
          name: tegami-pr-preview
          path: tegami-pr-preview.md
