name: Tests

on:
  pull_request:
    branches: ["*"]
    paths:
      - "packages/**"
      - "pnpm-lock.yaml"
  push:
    branches: ["main", "tegami/version-packages"]
    paths:
      - "packages/**"
      - "pnpm-lock.yaml"
  merge_group:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to run CI for"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read
  pull-requests: read
  checks: write
  statuses: write

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  FORCE_COLOR: 3

jobs:
  node_versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24, 26]
    name: Test (Node.js ${{ matrix.node-version }})
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - shell: bash
        run: pnpm install

      - name: Build packages
        run: |
          pnpm --filter "./packages/*" build

      - name: Unit tests
        run: pnpm test
